USER_APP_OBJS =	output/userApp/main.o \
                output/userApp/shell.o \
                output/userApp/memTestCase.o \
                output/userApp/TestCaseFCFS.o \
                output/userApp/TestCaseRR.o \
                output/userApp/TestCaseSJF.o
