include $(SRC_RT)/myOS/kernel/mem/Makefile
include $(SRC_RT)/myOS/kernel/time/Makefile

KERNEL_OBJS = output/myOS/kernel/scheduler.o \
		  output/myOS/kernel/task.o \
		  ${MEM_OBJS} \
		  ${TIME_OBJS}
